((topmost-intro . 1))
((class-open . 1))
((inclass . 20) (topmost-intro . 22))
((inclass . 20) (inline-open))
((defun-block-intro . 40))
((statement . 43))
((class-open . 54))
((inclass . 65) (topmost-intro . 67))
((inclass . 65) (inline-open))
((defun-block-intro . 89))
((inline-close . 89))
((class-close . 54))
((statement-cont . 113))
((inline-close . 40))
((class-close . 1))
