((topmost-intro . 1))
((inher-intro . 1))
((inher-cont . 21))
((class-open . 1))
((inclass . 65) (topmost-intro . 67))
((func-decl-cont . 69))
((func-decl-cont . 69))
((inclass . 1) (inline-open))
((inline-close . 208))
((inclass . 65) (topmost-intro . 210))
((inclass . 65) (topmost-intro . 210))
((inclass . 1) (inline-open))
((inline-close . 241))
((class-close . 1))
((topmost-intro . 249))
((topmost-intro . 249))
((inher-cont . 270))
((class-open . 252))
