((topmost-intro . 1))
((extern-lang-open . 1))
((inextern-lang) (topmost-intro . 14))
((defun-open . 18))
((defun-block-intro . 65))
((statement . 75))
((defun-close . 65))
((extern-lang-close . 1))
((topmost-intro . 109))
((topmost-intro . 109))
((extern-lang-open . 112))
((inextern-lang) (topmost-intro . 131))
((extern-lang-close . 112))
