((topmost-intro . 1))
((defun-open . 1))
((defun-block-intro . 28))
((inexpr-statement) (block-open . 34))
((statement-block-intro . 46))
((statement . 53))
((else-clause . 81))
((statement . 81))
((block-close . 46))
((arglist-close . 34))
((statement . 34))
((inexpr-statement) (statement-block-intro . 137))
((statement . 150))
((inexpr-statement) (block-close . 137))
((arglist-close . 142))
((substatement . 137))
((statement . 137))
((inexpr-statement) (statement-block-intro . 237) (statement . 237))
((inexpr-statement) (block-close . 237))
((defun-close . 28))
((topmost-intro . 286))
((defun-block-intro . 288))
((statement-cont . 305))
((block-open . 319))
((statement-block-intro . 322))
((block-close . 322))
((arglist-close . 319))
((statement . 305))
((statement-cont . 347))
((statement-block-intro . 361))
((block-close . 361))
((statement . 347))
((inexpr-statement) (statement-block-intro . 381) (statement . 381))
((inexpr-statement) (block-close . 381))
((defun-close . 288))
