((topmost-intro . 1))
((defun-open . 1))
((defun-block-intro . 28))
((inexpr-statement) (block-open . 34))
((statement-block-intro . 46))
((statement . 53))
((else-clause . 81))
((statement . 81))
((block-close . 46))
((arglist-close . 34))
((statement . 34))
((inexpr-statement) (statement-block-intro . 137))
((statement . 150))
((inexpr-statement) (block-close . 137))
((arglist-close . 137))
((substatement . 137))
((statement . 137))
((statement . 203))
((inexpr-statement) (block-close . 203))
((defun-close . 28))
