((topmost-intro . 1))
((inher-intro . 16))
((inher-cont . 10))
((class-open . 1))
((inclass . 39) (access-label . 49))
((inclass . 39) (topmost-intro . 41))
((inher-intro . 54))
((inher-cont . 65))
((class-open . 54))
((class-close . 54))
((class-close . 1))
