((topmost-intro . 1))
((defun-open . 1))
((defun-block-intro . 41))
((inlambda) (defun-block-intro . 47))
((statement . 81))
((inexpr-statement) (statement-block-intro . 102))
((inexpr-statement) (block-close . 102))
((inlambda) (inline-close . 47))
((statement . 47))
((inlambda) (lambda-intro-cont . 155))
((arglist-cont-nonempty . 176))
((inlambda) (defun-block-intro . 155))
((statement . 205))
((inexpr-statement) (block-open . 222))
((inlambda) (inline-close . 155))
((statement . 155))
((arglist-cont-nonempty . 276))
((inlambda) (defun-block-intro . 271))
((statement . 271))
((inlambda) (lambda-intro-cont . 340))
((arglist-cont-nonempty . 361))
((inlambda) (inline-open . 340))
((statement . 391))
((inexpr-statement) (block-open . 412))
((statement . 340))
((arglist-intro . 449))
((arglist-cont . 475))
((inlambda) (defun-block-intro . 499))
((inlambda) (inline-close . 499))
((defun-close . 41))
