((topmost-intro . 1))
((defun-open . 1))
((defun-block-intro . 41))
((inlambda) (statement-block-intro . 47))
((statement . 81))
((inexpr-statement) (statement-block-intro . 102))
((inexpr-statement) (block-close . 102))
((inlambda) (inline-close . 47))
((statement . 47))
((inlambda) (lambda-intro-cont . 155))
((arglist-cont-nonempty . 176))
((inlambda) (inline-open . 155))
((statement . 206))
((inexpr-statement) (block-open . 227))
((inline-close . 206))
((statement . 155))
((arglist-intro . 272))
((arglist-cont . 298))
((inlambda) (statement-block-intro . 322))
((inlambda) (inline-close . 322))
((defun-close . 41))
