((topmost-intro . 1))
((defun-open . 1))
((defun-block-intro . 41))
((inlambda . 47) (inexpr-block-intro))
((statement . 81))
((inexpr-statement . 102) (inexpr-block-intro))
((inexpr-statement . 102) (inexpr-block-close))
((inlambda . 47) (inexpr-block-close))
((statement . 47))
((inlambda . 154) (lambda-intro-cont))
((arglist-cont-nonempty . 175))
((inlambda . 154) (inexpr-block-open))
((statement . 205))
((inexpr-statement . 226) (inexpr-block-open))
((inlambda . 205) (inexpr-block-close))
((statement . 154))
((arglist-intro . 274))
((arglist-cont . 300))
((inlambda . 324) (inexpr-block-intro))
((inlambda . 324) (inexpr-block-close))
((defun-close . 41))
