((comment-intro) (topmost-intro . 1))
((c . 1))
((topmost-intro . 1))
((cpp-macro) (topmost-intro . 1))
((cpp-macro-cont . 116))
((cpp-macro) (topmost-intro . 1))
((cpp-macro) (topmost-intro . 1))
((arglist-cont-nonempty . 167))
((cpp-macro) (topmost-intro . 1))
((cpp-macro) (topmost-intro . 1))
((cpp-define-intro) (knr-argdecl-intro . 220))
((cpp-macro) (topmost-intro . 1))
((arglist-cont-nonempty . 269))
((arglist-close . 269))
((cpp-define-intro . 269))
((topmost-intro . 1))
((topmost-intro . 1))
((defun-block-intro . 321))
((cpp-macro) (statement . 335))
((cpp-macro-cont . 342))
((cpp-macro) (statement . 335))
((cpp-macro) (statement . 335))
((arglist-cont-nonempty . 393))
((cpp-macro) (statement . 335))
((cpp-macro) (statement . 335))
((statement-cont . 459))
((cpp-macro) (statement . 335))
((arglist-cont-nonempty . 497))
((arglist-close . 497))
((cpp-define-intro . 497))
((defun-close . 321))
((topmost-intro . 548))
((topmost-intro . 548))
((cpp-macro) (arglist-cont-nonempty . 551))
((cpp-macro-cont . 565))
((cpp-macro) (arglist-cont-nonempty . 551))
((cpp-macro) (arglist-cont-nonempty . 551))
((arglist-cont-nonempty . 616))
((cpp-macro) (arglist-cont-nonempty . 551))
((cpp-macro) (arglist-cont-nonempty . 551))
((arglist-cont-nonempty . 551))
((cpp-macro) (arglist-cont-nonempty . 551))
((arglist-cont-nonempty . 724))
((arglist-close . 724))
((cpp-define-intro . 724))
((arglist-close . 551))
((topmost-intro . 778))
((cpp-macro) (topmost-intro . 778))
((cpp-define-intro . 786))
((knr-argdecl-intro . 815))
((defun-open . 815))
