((cpp-macro) (topmost-intro . 1))
((cpp-macro-cont . 1))
((brace-list-close . 41))
((cpp-macro-cont) (topmost-intro . 101))
((brace-list-close . 121))
((topmost-intro . 1))
((cpp-macro) (topmost-intro . 1))
((cpp-macro-cont . 164))
((cpp-macro-cont) (topmost-intro . 212))
((substatement . 245))
((substatement . 300))
((else-clause . 300))
