((topmost-intro . 1))
((innamespace) (topmost-intro . 17))
((innamespace) (topmost-intro . 18))
((defun-close . 22))
((innamespace) (topmost-intro . 35))
((namespace-close . 1))
((topmost-intro . 46))
((topmost-intro . 46))
((topmost-intro . 46))
((namespace-open . 50))
((innamespace) (topmost-intro . 66))
((innamespace) (topmost-intro . 67))
((defun-open . 71))
((defun-close . 86))
((innamespace) (topmost-intro . 88))
((namespace-close . 50))
