((topmost-intro . 1))
((class-open . 1))
((inclass . 18) (topmost-intro . 20))
((inclass . 1) (inline-open))
((defun-block-intro . 50))
((substatement-open . 58))
((statement-block-intro . 86))
((block-close . 86))
((inline-close . 50))
((inclass . 18) (topmost-intro . 117))
((inclass . 1) (inline-open))
((defun-block-intro . 165))
((inline-close . 165))
((class-close . 1))
