((topmost-intro . 1))
((class-open . 1))
((inclass . 9) (topmost-intro . 11))
((inclass . 9) (topmost-intro . 11))
((class-open . 51))
((inclass . 51) (access-label . 91))
((inclass . 78) (topmost-intro . 80))
((inclass . 51) (inline-open))
((defun-block-intro . 106))
((inline-close . 106))
((class-close . 51))
((class-close . 1))
